# Site settings
baseurl = "https://peatheads.github.io/peatheads/"
languageCode = "de-de"
title = "Peatheads - Whisky Blog"
theme = "hugo-agency-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = ""
canonifyurls = "true"

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) or
	# most longer texts.
	#
	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Peatheads"
	description = "Whisky Blog"

	# Since this template is static, the contact form uses www.formspree.io as a
	# proxy. The form makes a POST request to their servers to send the actual
	# email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
	email = "your@email.com"

    # Link custom assets relative to /static
    custom_css = []
    custom_js  = []


	# Navigation
	[params.navigation]
		brand = "Peatheads"
		services = "Content"
		team = "Heads"
		contact = "Kontakt"

    # Add custom links. Those can be pre- and postpended to the default menu above.
    # Use the weight attribute to order your custom links. Uncomment the example
    # below and replace the values with your own.

    # prepended links
    #[[menu.prepend]]
    #    url = "http://gohugo.io"
    #    name = "Hugo"
    #    weight = 10

    # postpended links
    [[menu.postpend]]
        url = "http://gohugo.io"
        name = "External link"
        weight = 10


	# Hero section
	[params.hero]
		# To change the background image of the hero, replace 'header-bg.jpg' in
		# the 'static/img' folder.
		title = "Peatheads"
		subtitle = "Heavenly Peated"
		buttonText = "Weiter gehts"


	# about section
	[params.services]
        enable = true
		title = "Content"
		subtitle = "Die Peatheads geben zum Besten."

        [[params.services.row]]

            [[params.services.row.list]]
                icon = "fa-laptop"
                title = "Blog"
                description = "In unserem Blog findet ihr Neuigkeiten rund um Whisky die wir mitteilenswert finden."

            [[params.services.row.list]]
                icon = "fa-youtube-play"
                title = "Tastings"
                description = "Bei den Tastings widmen wir uns in der Regel einem oder mehreren Tropfen und verk√∂stigen diese."


	# Team section
	[params.team]
        enable = true
		title = "Heads"
		subtitle = "Die Heads stellen sich vor."

		# All team member's pictures are stored under 'static/img/team'.
		# Replace them with your own too.
		[[params.team.members]]
			img = "1.jpg"
			name = "Ole Olsson"
			position = "Peatrocker"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "2.jpg"
			name = "Andre Anderson"
			position = "Peatbrother"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

		[[params.team.members]]
			img = "3.jpg"
			name = "Daniel Dalsson"
			position = "Peatnose"
			social = [
				["fa-twitter", "#"],
				["fa-facebook", "#"],
				["fa-linkedin", "#"]
			]

	# Contact section
	[params.contact]
        enable = true
		title = "Contact us"
		subtitle  = "Lorem ipsum dolor sit amet consectetur."
		buttonText = "Send message"

		# 'warning' defines error messages for invalid inputs
		[params.contact.form.name]
			text = "Your Name *"
			warning = "Please enter your name."

		[params.contact.form.email]
			text = "Your Email *"
			warning = "Please enter your email address."

		[params.contact.form.phone]
			text = "Your Phone *"
			warning = "Please enter your phone number."

		[params.contact.form.message]
			text = "Your Message *"
			warning = "Please enter a message."


	# Footer section
	[params.footer]
        enable = true
		copyright = "Published under the Apache License 2.0."

		[[params.footer.social]]
			icon = "fa-twitter"
			link = "#"

		[[params.footer.social]]
			icon = "fa-facebook"
			link = "#"

		[[params.footer.social]]
			icon = "fa-linkedin"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Privacy Policy"
			link = "#"

		[[params.footer.quicklinks]]
			text = "Terms of Use"
			link = "#"
